services:
  # Backend API
  - type: web
    name: techfolks-backend
    runtime: node
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    buildCommand: cd techfolks/backend && npm install && npm run build
    startCommand: cd techfolks/backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: techfolks-db
          property: connectionString
      - key: REDIS_URL
        value: redis://default:YOUR_PASSWORD@redis-12345.upstash.io:12345
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JUDGE0_API_URL
        value: https://judge0-ce.p.rapidapi.com
      - key: RAPIDAPI_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://techfolks-frontend.onrender.com

  # Frontend Static Site
  - type: web
    name: techfolks-frontend
    runtime: static
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
    buildCommand: cd techfolks/backend/techfolks/frontend && npm install && npm run build
    staticPublishPath: ./techfolks/backend/techfolks/frontend/dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options  
        value: nosniff
    envVars:
      - key: VITE_API_URL
        value: https://techfolks-backend.onrender.com/api
      - key: VITE_WS_URL
        value: wss://techfolks-backend.onrender.com

databases:
  - name: techfolks-db
    plan: free
    databaseName: techfolks
    user: techfolks
    region: oregon